server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /utdanning/larling
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer
  codec:
    max-in-memory-size: 200MB
    consumer:
      group-id: # consumer-personvern-samtykke-<your-instance-id>

fint:
  security:
    open-paths: |
      /api-docs/**,
      /swagger/**,
      /actuator/prometheus
  consumer:
    org-id: nfk.no
    domain: utdanning
    package: larling
  kafka:
    application-id: consumer-utdanning-larling
    enable-ssl: false
    default-replicas: 1
    topic:
      org-id: nfk.no
      domain-context: fint-core

logging:
  level:
    root: INFO
    no.fintlabs.kafka: WARN
    org:
      apache.kafka: WARN
      springframework:
        kafka: WARN
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus