server:
  port: 8080

spring:
  security:
    open-paths: |
      /api-docs/**,
      /swagger/**
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  webflux:
    base-path: /utdanning/larling
  kafka:
    consumer:
      group-id: # consumer-utdanning-vurdering-<your-instance-id>


fint:
  consumer:
    org-id:
    domain:
    package:
  kafka:
    application-id: consumer-utdanning-larling
    enable-ssl: true
    topic:
      org-id: fintlabs.no
      domain-context: fint-core

logging:
  level:
    org.springdoc: DEBUG
    root: INFO
    no.fintlabs.kafka: WARN
    org:
      apache.kafka: WARN
      springframework:
        kafka: WARN
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/ui