apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-core-consumer-utdanning-vurdering
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`alpha.felleskomponent.no`) && (PathPrefix( `/utdanning/vurdering`) || Path(`/utdanning/vurdering/admin`)) && Headers(`x-org-id`, `fintlabs.no`)"
      kind: Rule
      services:
        - name: fint-core-consumer-utdanning-vurdering
          port: 8080